ansible_user: "${ANSIBLE_USER}"
ansible_password: "${ANSIBLE_PASSWORD}"
dotfiles_path: "${DOTFILES_HOME}"
home_path: "${HOME}"
global_tasks: roles/global/tasks

macos:
  vscode:
    links:
      - settings.json
    extensions:
      - file-icons.file-icons
      - jeff-hykin.better-shellscript-syntax
      - maximilionus.dark-shell
      - ms-azuretools.vscode-docker
      - ms-python.python
      - ms-python.vscode-pylance
      - ms-toolsai.jupyter
      - ms-toolsai.jupyter-keymap
      - ms-toolsai.jupyter-renderers
      - ms-vscode-remote.remote-containers
      - PKief.material-icon-theme
      - AmazonWebServices.aws-toolkit-vscode