- set_fact:
    vscode: {}
    vscode_settings_path: '{{ home_path }}/Library/Application\ Support/Code/User'

- name: vscode_settings
  ansible.builtin.debug:
    msg: "{{ item }}"
  loop_control:
    label: '{{ item }}'
  with_list: '{{ macos.vscode.links }}'

- name: create symlinks
  command: |
    ln -s -f {{ dotfiles_path }}/config/vscode/{{ item }} {{ vscode_settings_path }}
  loop_control:
    label: '{{ item }}'
  with_list: '{{ macos.vscode.links }}'
  when: macos.vscode.links

- name: get installed extensions
  command: code --list-extensions
  register: installed_vscode_exts

- name: install extensions
  command: code --install-extension {{ item | quote }}
  when: |
    macos.vscode.extensions and installed_vscode_exts.stdout.find(item) == -1
  with_items: '{{ macos.vscode.extensions }}'