ansible_user: "${ANSIBLE_USER}"
dotfiles_path: "${DOTFILES_HOME}"
home_path: "${HOME}"
alacritty_path: "/Applications/Alacritty.app"
common_tasks: "roles/macos/common/tasks"
homebrew_path: /opt/homebrew/bin