---
- name: Check for alacritty
  stat:
      path: '{{ alacritty_path }}'
  register: alacritty_stat
  changed_when: not (alacritty_stat.stat.exists
    and alacritty_stat.stat.executable)

- name: install alacritty
  shell: brew install --cask --no-quarantine alacritty
  when: alacritty_stat is changed

- stat: path={{ lookup('env', 'HOME') }}/.config/alacritty.yml
  register: alacritty_conf

- name: link alacritty
  command: |
    ln -s -f {{ dotfiles_path }}/config/alacritty.yml {{ lookup('env', 'HOME') }}/.config/alacritty.yml
  when: not alacritty_conf.stat.exists
