---
- include: brew.yaml
  tags: ["homebrew"]
- include: shell.yaml
  tags: ["zshrc", "bashrc"]
- include: alacritty.yaml
  tags: ["alacritty"]
- import_tasks: "{{ common_tasks }}/vscode.yaml"
  tags: ["vscode"]