---
- name: Check for alacritty
  stat:
      path: '{{ alacritty_path }}'
  register: alacritty_stat
  changed_when: not (alacritty_stat.stat.exists
    and alacritty_stat.stat.executable)

- name: install alacritty
  shell: brew install --cask --no-quarantine alacritty
  when: alacritty_stat is changed