name: Tests
on:
  push:
  pull_request:

jobs:
  osx:
    runs-on: macos-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Run install
        run : ./setup.sh