name: Tests
on:
  push:
  pull_request:

jobs:
  osx:
    runs-on: macos-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set Permissions
        run : chmod +x run.sh
      - name: Run install
        run : ./run.sh bootstrap

  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
      - name: Set Permissions
        run : chmod +x run.sh
      - name: Run install
        run : ./run.sh bootstrap