name: Tests
on:
  push:
  pull_request:

jobs:
  osx:
    name: Run full installation
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Run install
        run : ./setup.sh